# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_duration',
            field=models.IntegerField(default=2),
        ),
    ]
