# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_catalog', '0005_course_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(max_length=200),
        ),
    ]
