# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_catalog', '0006_auto_20160110_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.TextField(),
        ),
    ]
