# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_catalog', '0007_auto_20160110_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_duration',
            field=models.CharField(choices=[('2', '2 weeks'), ('8', '8 weeks')], max_length=100),
        ),
    ]
