# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_catalog', '0008_auto_20160110_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses'),
        ),
    ]
