# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_catalog', '0009_auto_20160110_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.FileField(null=True, upload_to=None),
        ),
    ]
