# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_catalog', '0012_auto_20160111_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.FileField(blank=True, null=True, upload_to='None/'),
        ),
    ]
