# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_catalog', '0013_auto_20160111_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
