# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 01:13
from __future__ import unicode_literals

import course_catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_catalog', '0014_auto_20160111_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to=course_catalog.models.get_image_path),
        ),
    ]
